# Generated by Django 2.1.2 on 2018-10-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('begin_date', models.DateField(verbose_name='date been selected')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('team_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NbaSite.Team'),
        ),
    ]
